MailSenderApp/Controllers/AccountController.cs
using System;
using System.Globalization;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using MailSenderApp.Models;

namespace MailSenderApp.Controllers
{
    [Authorize]
    public class AccountController : Controller
    {
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public AccountController()
        {
        }

        public AccountController(ApplicationUserManager userManager, ApplicationSignInManager signInManager )
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set 
            { 
                _signInManager = value; 
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        //
        // GET: /Account/Login
        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        //
        // POST: /Account/Login
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Login(LoginViewModel model, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            // This doesn't count login failures towards account lockout
            // To enable password failures to trigger account lockout, change to shouldLockout: true
            var result = await SignInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, shouldLockout: false);
            switch (result)
            {
                case SignInStatus.Success:
                    return RedirectToLocal(returnUrl);
                case SignInStatus.LockedOut:
                    return View("Lockout");
                case SignInStatus.RequiresVerification:
                    return RedirectToAction("SendCode", new { ReturnUrl = returnUrl, RememberMe = model.RememberMe });
                case SignInStatus.Failure:
                default:
                    ModelState.AddModelError("", "Invalid login attempt.");
                    return View(model);
            }
        }

        //
        // GET: /Account/VerifyCode
        [AllowAnonymous]
        public async Task<ActionResult> VerifyCode(string provider, string returnUrl, bool rememberMe)
        {
            // Require that the user has already logged in via username/password or external login
            if (!await SignInManager.HasBeenVerifiedAsync())
            {
                return View("Error");
            }
            return View(new VerifyCodeViewModel { Provider = provider, ReturnUrl = returnUrl, RememberMe = rememberMe });
        }

        //
        // POST: /Account/VerifyCode
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> VerifyCode(VerifyCodeViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            // The following code protects for brute force attacks against the two factor codes. 
            // If a user enters incorrect codes for a specified amount of time then the user account 
            // will be locked out for a specified amount of time. 
            // You can configure the account lockout settings in IdentityConfig
            var result = await SignInManager.TwoFactorSignInAsync(model.Provider, model.Code, isPersistent:  model.RememberMe, rememberBrowser: model.RememberBrowser);
            switch (result)
            {
                case SignInStatus.Success:
                    return RedirectToLocal(model.ReturnUrl);
                case SignInStatus.LockedOut:
                    return View("Lockout");
                case SignInStatus.Failure:
                default:
                    ModelState.AddModelError("", "Invalid code.");
                    return View(model);
            }
        }

        //
        // GET: /Account/Register
        [AllowAnonymous]
        public ActionResult Register()
        {
            return View();
        }

        //
        // POST: /Account/Register
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Register(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser 
                { 
                    UserName = model.Email, 
                    Email = model.Email,
                };
                var result = await UserManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    await SignInManager.SignInAsync(user, isPersistent:false, rememberBrowser:false);
                    
                    // For more information on how to enable account confirmation and password reset please visit https://go.microsoft.com/fwlink/?LinkID=320771
                    // Send an email with this link
                    // string code = await UserManager.GenerateEmailConfirmationTokenAsync(user.Id);
                    // var callbackUrl = Url.Action("ConfirmEmail", "Account", new { userId = user.Id, code = code }, protocol: Request.Url.Scheme);
                    // await UserManager.SendEmailAsync(user.Id, "Confirm your account", "Please confirm your account by clicking <a href=\"" + callbackUrl + "\">here</a>");

                    return RedirectToAction("Index", "Home");
                }
                AddErrors(result);
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        //
        // GET: /Account/ConfirmEmail
        [AllowAnonymous]
        public async Task<ActionResult> ConfirmEmail(string userId, string code)
        {
            if (userId == null || code == null)
            {
                return View("Error");
            }
            var result = await UserManager.ConfirmEmailAsync(userId, code);
            return View(result.Succeeded ? "ConfirmEmail" : "Error");
        }

        //
        // GET: /Account/ForgotPassword
        [AllowAnonymous]
        public ActionResult ForgotPassword()
        {
            return View();
        }

        //
        // POST: /Account/ForgotPassword
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ForgotPassword(ForgotPasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByNameAsync(model.Email);
                if (user == null || !(await UserManager.IsEmailConfirmedAsync(user.Id)))
                {
                    // Don't reveal that the user does not exist or is not confirmed
                    return View("ForgotPasswordConfirmation");
                }

                // For more information on how to enable account confirmation and password reset please visit https://go.microsoft.com/fwlink/?LinkID=320771
                // Send an email with this link
                // string code = await UserManager.GeneratePasswordResetTokenAsync(user.Id);
                // var callbackUrl = Url.Action("ResetPassword", "Account", new { userId = user.Id, code = code }, protocol: Request.Url.Scheme);		
                // await UserManager.SendEmailAsync(user.Id, "Reset Password", "Please reset your password by clicking <a href=\"" + callbackUrl + "\">here</a>");
                // return RedirectToAction("ForgotPasswordConfirmation", "Account");
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        //
        // GET: /Account/ForgotPasswordConfirmation
        [AllowAnonymous]
        public ActionResult ForgotPasswordConfirmation()
        {
            return View();
        }

        //
        // GET: /Account/ResetPassword
        [AllowAnonymous]
        public ActionResult ResetPassword(string code)
        {
            return code == null ? View("Error") : View();
        }

        //
        // POST: /Account/ResetPassword
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ResetPassword(ResetPasswordViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var user = await UserManager.FindByNameAsync(model.Email);
            if (user == null)
            {
                // Don't reveal that the user does not exist
                return RedirectToAction("ResetPasswordConfirmation", "Account");
            }
            var result = await UserManager.ResetPasswordAsync(user.Id, model.Code, model.Password);
            if (result.Succeeded)
            {
                return RedirectToAction("ResetPasswordConfirmation", "Account");
            }
            AddErrors(result);
            return View();
        }

        //
        // GET: /Account/ResetPasswordConfirmation
        [AllowAnonymous]
        public ActionResult ResetPasswordConfirmation()
        {
            return View();
        }

        //

MailSenderApp/Controllers/HomeController.cs
using MailSenderApp.Models;
using MailSenderApp.Models.Domains;
using MailSenderApp.Models.Repositories;
using MailSenderApp.Models.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace MailSenderApp.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private EmailRepository _emailRepository = new EmailRepository();
        private EmailParametersRepository _emailParametersRepository = new EmailParametersRepository();
        private EmailSender _emailSender;
        private static readonly NLog.Logger Logger = NLog.LogManager.GetCurrentClassLogger();

        [Authorize]
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            var emails = _emailRepository.GetEmails(userId);
            return View(emails);
        }
        public ActionResult Email(int id = 0)
        {
            var userId = User.Identity.GetUserId();
            var email = id == 0 ?
                SentEmail(userId) : _emailRepository.GetEmail(id, userId);
            
            var vm = PrepareEmailVm(email, userId);

            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> NewEmail(Email email)
        {
            var userId = User.Identity.GetUserId();
            var emailParameters = _emailParametersRepository.GetEmailParameters(email.EmailParams.Id, userId);
            try
            {
                _emailSender = new EmailSender(emailParameters);
                await _emailSender.Send(email);
                _emailRepository.AddMail(email);

            }
            catch (Exception ex)
            {
                Logger.Error(ex, ex.Message);
            
            }
            
            return RedirectToAction("Index");
        
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EmailParameters(EmailParams emailParameters)
        {
            var userId = User.Identity.GetUserId();
            emailParameters.UserId = userId;

            if (emailParameters.Id == 0)
                _emailParametersRepository.AddNewAccount(emailParameters);
            else
                _emailParametersRepository.UpdateAccount(emailParameters);

            return RedirectToAction("Accounts");

        }
        private EmailSenderViewModel PrepareEmailVm(Email email, string userId)
        {
            return new EmailSenderViewModel
            {
                Email = email,
                Heading = email.Id == 0 ? "Nowa wiadomość" : "Wysłana wiadomość",
                EmailParameters = _emailParametersRepository.GetEmailParameters(userId)
            };
        }

        private Email SentEmail(string userId)
        {
            return new Email 
            { 
                UserId = userId,
                SentDate = DateTime.Now,
            };
        }

        public ActionResult Accounts()
        {
            var userId = User.Identity.GetUserId();
            var emailParameters = _emailParametersRepository.GetEmailParameters(userId);
            return View(emailParameters);
        }
        public ActionResult EmailParameters(int id = 0)
        {
            var userId = User.Identity.GetUserId();
            var emailParameters = id == 0 ?
                AddEmailParameters(userId) : _emailParametersRepository.GetEmailParameters(id, userId);

            var vm = PrepareEmailParametersVm(emailParameters, userId);

            return View(vm);
        }

        private EmailParams AddEmailParameters(string userId)
        {
            return new EmailParams
            {
                UserId = userId
            };
        }

        private EmailParamsViewModel PrepareEmailParametersVm(EmailParams emailParameters, string userId)
        {
            return new EmailParamsViewModel
            {
                EmailParameters = emailParameters,
                Heading = emailParameters.Id == 0 ? "Dodaj nowe konto" : "Edycja konta"
            };
        }

        [HttpPost]
        public ActionResult DeleteEmail(int id)
        {
            try
            {
                var userId = User.Identity.GetUserId();
                _emailRepository.Delete(id, userId);
            }
            catch (Exception exception)
            {
                //NLOG logowanie
                return Json(new { Success = false, Message = exception.Message });
            }
            return Json(new { Success = true });
        }

        [HttpPost]
        public ActionResult DeleteAccount(int id)
        {
            try
            {
                var userId = User.Identity.GetUserId();
                _emailParametersRepository.Delete(id, userId);
            }
            catch (Exception exception)
            {
                //NLOG logowanie
                return Json(new { Success = false, Message = exception.Message });
            }
            return Json(new { Success = true });
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MailSenderApp/Controllers/PrintController.cs
using MailSenderApp.Models.Domains;
using MailSenderApp.Models.Repositories;
using Microsoft.AspNet.Identity;
using Rotativa;
using Rotativa.Options;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace MailSenderApp.Controllers
{
    public class PrintController : Controller
    {
        private EmailRepository _emailRepository = new EmailRepository();
        [Authorize]
        
        public ActionResult EmailToPdf(int id)
        {
            var handle = Guid.NewGuid().ToString();
            var userId = User.Identity.GetUserId();
            var email = _emailRepository.GetEmail(id, userId);

            TempData[handle] = GetPdfContent(email);

            return Json(new
            {
                FileGuid = handle,
                FileName = $@"Email_{email.Id}.pdf"
            });
        }

        private byte[] GetPdfContent(Email email)
        {
            var pdfResult = new ViewAsPdf(@"PrintEmail", email)
            {
                PageSize = Rotativa.Options.Size.A4,
                PageOrientation = Rotativa.Options.Orientation.Portrait
            };

            return pdfResult.BuildFile(ControllerContext);
        }

        public ActionResult DownloadEmailPdf(string fileGuid, string fileName)
        {
            if (TempData[fileGuid] == null)
                throw new Exception("Błąd przy próbie eksportu email do PDF.");

            var data = TempData[fileGuid] as byte[];
            return File(data, "application/pdf", fileName);
        }

        public ActionResult PrintEmail(int id)
        {
            var userId = User.Identity.GetUserId();
            var emailToPrint = _emailRepository.GetEmail(id, userId);

            return View("PrintEmail", emailToPrint);
        }

    }
}

MailSenderApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MailSenderApp/Views/Home/Accounts.cshtml
@model IEnumerable<MailSenderApp.Models.Domains.EmailParams>
@{
    ViewBag.Title = "Konta email do wysyłania wiadomości";
}

<h1 class="mb-4">Konta email do wysyłania wiadomości</h1>

<button type="button" class="btn btn-outline-success mb-3"
        onclick='window.location.href="@Url.Action("EmailParameters","Home")"'>
    Dodaj konto
</button>

@if (Model != null && Model.Any())
{
    <table class="table table-hover table-striped mt-3 mb-5">
        <thead>
            <tr>
                <th scope="col">Nazwa konta</th>
                <th scope="col">Email</th>
                <th scope="col">Host Smtp</th>
                <th scope="col">Port</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var account in Model)
            {
                <tr>
                    <td>
                        <a href="@Url.Action("EmailParameters","Home", new { id = account.Id})">@account.SenderName</a>
                    </td>
                    <td>@account.SenderEmail</td>
                    <td>@account.HostSmtp</td>
                    <td>@account.Port</td>
                    <td>
                        <button class="btn btn-danger btn-sm"
                                onclick="deleteAccount('@account.Id', this)">
                            Usuń konto
                        </button>
                    </td>
                </tr>

            }
        </tbody>
    </table>
}
else
{
    <div>
        Brak dodanych kont
    </div>
}

@section Scripts
{
    <script type="text/javascript">
        function deleteAccount(id, btn)
        {
            if (!confirm("Czy napewno chcesz usunąć konto?"))
                return;

            $.ajax({
                type: 'POST',
                url: "@Url.Action("DeleteAccount","Home")",
                data: { id: id },
                success: function (data)
                {
                    if (data.Success)
                    {
                        var row = btn.parentNode.parentNode;
                        row.parentNode.removeChild(row);
                    }
                    else
                    {
                        alert(data.Message);
                    }
                },
                error: function (data)
                {
                    alert(data.Message);
                },
                datatype: 'json'
            });
        }
    </script>
}

MailSenderApp/Views/Home/Email.cshtml
@model MailSenderApp.Models.ViewModels.EmailSenderViewModel

@{
    ViewBag.Title = Model.Heading;
}

<h2 class="mb-3">@Model.Heading</h2>

@if (Model.Email.Id != 0)
{
    <button class="btn btn-secondary mb-3" onclick="generatePdf()">
        Generuj PDF
    </button>
    <button class="btn btn-secondary mb-3" onclick="printEmail()">
        Drukuj
    </button>
}

<div class="row">
    <div class="col-lg-6">
        @using (Html.BeginForm("NewEmail", "Home"))
        {
            @Html.AntiForgeryToken()

            if (Model.Email.Id == 0)
            {
                <p class="alert alert-info mt-4 mb-4">
                    Pola Tytuł, Do i Treść wiadomości są <strong>wymagane</strong>
                </p>
            }

            @Html.HiddenFor(x => x.Email.Id)
            @Html.HiddenFor(x => x.Email.UserId)

            <div class="form-group mt-3">
                @Html.LabelFor(x => x.Email.EmailParams.Id)
                @Html.DropDownListFor(x => x.Email.EmailParams.Id, new SelectList(Model.EmailParameters, "Id", "SenderName"),
                    "--Wybierz konto--", new { @class = "form-control" })
            </div>

            <div class="form-group mt-3">
                @Html.LabelFor(x => x.Email.Title, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(x => x.Email.Title, new { @class = "form-control", autofocus = "autofocus" })
                    @Html.ValidationMessageFor(x => x.Email.Title)
                </div>
            </div>

            <div class="form-group mt-3">
                @Html.LabelFor(x => x.Email.RecipientAddress, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(x => x.Email.RecipientAddress, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Email.RecipientAddress)
                </div>
            </div>

            <div class="form-group mt-3">
                @Html.LabelFor(x => x.Email.CcAddress, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(x => x.Email.CcAddress, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Email.CcAddress)
                </div>
            </div>

            <div class="form-group mt-3">
                @Html.LabelFor(x => x.Email.Message, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextAreaFor(x => x.Email.Message, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Email.Message)
                </div>
            </div>

            <div class="form-group mt-3">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" class="btn btn-primary mt-3 mb-5" value="Wyślij i zapisz" />
                </div>
            </div>
        }
    </div>
</div>

@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/4.0.20/tinymce.min.js"></script>
    <script type="text/javascript">
        tinymce.init({
            selector: 'textarea',
            width: 600,
            height: 300
        });
    </script>

    <script type="text/javascript">

        function generatePdf() {

            $.ajax({
                type: 'POST',
                url: "@Url.Action("EmailToPdf", "Print")",
                data: {
                    id: '@Model.Email.Id'
                },
                success: function (data) {
                    window.location = '@Url.Action("DownloadEmailPdf", "Print")' + '?fileGuid=' + data.FileGuid + '&fileName=' + data.FileName;
                },
                error: function (data) {
                    alert(data.Message);
                },
                dataType: 'json',
                cache: false
            });

        }

        function printEmail() {

            var windowUrl = '@Url.Action("PrintEmail", "Print")' + '?id=' + '@Model.Email.Id';
            var printWindow = window.open(windowUrl, '', 'top = 100, left = 200, width = 500, height = 500');
            printWindow.print();
        }


        $(document).ready(function () {

            $.validator.methods.number = function (value, element) {
                return this.optional(element) || /^-?(?:\d+|\d{1,3}(?:[\s\.,]\d{3})+)(?:[\.,]\d+)?$/.test(value);
            }

            $.validator.methods.date = function (value, element) {
                var isChrome = /Chrome/.test(navigator.userAgent) && /Google Inc/.test(navigator.vendor);
                if (isChrome) {
                    var d = new Date();
                    return this.optional(element) || !/Invalid|NaN/.test(new Date(d.toLocaleDateString(value)));
                } else {
                    return this.optional(element) || !/Invalid|NaN/.test(new Date(value));
                }
            };

        });
    </script>
}

MailSenderApp/Views/Home/EmailParameters.cshtml
@model MailSenderApp.Models.ViewModels.EmailParamsViewModel

@{
    ViewBag.Title = Model.Heading;
}

<h2 class="mb-3">@Model.Heading</h2>

<div class="row">
    <div class="col-lg-6">
        @using (Html.BeginForm("EmailParameters", "Home"))
        {
            @Html.AntiForgeryToken()

            if (Model.EmailParameters.Id == 0)
            {
                <p class="alert alert-info mt-4 mb-4">
                    Wszystkie pola są <strong>wymagane</strong>
                </p>
            }

            @Html.HiddenFor(x => x.EmailParameters.Id)
            @Html.HiddenFor(x => x.EmailParameters.UserId)

            <div class="form-group mt-3">
                @Html.LabelFor(x => x.EmailParameters.HostSmtp, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(x => x.EmailParameters.HostSmtp, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.EmailParameters.HostSmtp)
                </div>
            </div>

            <div class="form-group mt-3">
                @Html.LabelFor(x => x.EmailParameters.EnableSsl, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.CheckBoxFor(x => x.EmailParameters.EnableSsl, new
                    { @class="form-check-input", type="checkbox", value="true", id= Model.EmailParameters.EnableSsl })
                    @Html.ValidationMessageFor(x => x.EmailParameters.EnableSsl)
                </div>
            </div>

            <div class="form-group mt-3">
                @Html.LabelFor(x => x.EmailParameters.Port, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(x => x.EmailParameters.Port, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.EmailParameters.Port)
                </div>
            </div>

            <div class="form-group mt-3">
                @Html.LabelFor(x => x.EmailParameters.SenderEmail, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(x => x.EmailParameters.SenderEmail, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.EmailParameters.SenderEmail)
                </div>
            </div>

            <div class="form-group mt-3">
                @Html.LabelFor(x => x.EmailParameters.SenderEmailPassword, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(x => x.EmailParameters.SenderEmailPassword, new
                    { @class = "form-control", type = "password" })
                    @Html.ValidationMessageFor(x => x.EmailParameters.SenderEmailPassword)
                </div>
            </div>

            <div class="form-group mt-3">
                @Html.LabelFor(x => x.EmailParameters.SenderName, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(x => x.EmailParameters.SenderName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.EmailParameters.SenderName)
                </div>
            </div>

            <div class="form-group mt-3">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" class="btn btn-primary mt-3 mb-5" value="Zapisz" />
                </div>
            </div>

        }
    </div>
 </div>

MailSenderApp/Views/Home/Index.cshtml
@model IEnumerable<MailSenderApp.Models.Domains.Email>
@{
    ViewBag.Title = "Wysłane wiadomości";
}

<h1 class="mb-4">Wysłane wiadomości</h1>

<button type="button" class="btn btn-outline-primary mb-3" 
        onclick='window.location.href="@Url.Action("Email","Home")"'>
            Wyślij nową wiadomość
</button>
<button type="button" class="btn btn-outline-primary mb-3"
        onclick='window.location.href="@Url.Action("Accounts","Home")"'>
            Konta e-mail
</button>

@if (Model != null && Model.Any())
{
    <table class="table table-hover table-striped mt-3 mb-5">
        <thead>
            <tr>
                <th scope="col">Data wysłania</th>
                <th scope="col">Adresat</th>
                <th scope="col">DW</th>
                <th scope="col">Tytuł wiadomości</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var email in Model)
            {
                <tr>
                    <td>@email.SentDate.ToString("G")</td>
                    <td>@email.RecipientAddress</td>
                    <td>@email.CcAddress</td>
                    <td>
                        <a href="@Url.Action("Email","Home", new { id = email.Id})">@email.Title</a>
                    </td>
                    <td>
                        <button class="btn btn-danger btn-sm"
                                onclick="deleteEmail('@email.Id', this)">
                            Usuń wiadomość
                        </button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div>
        Brak wysłanych wiadomości
    </div>
}

@section Scripts
{
    <script type="text/javascript">
        function deleteEmail(id, btn)
        {
            if (!confirm("Czy napewno chcesz usunąć wiadomość?"))
                return;

            $.ajax({
                type: 'POST',
                url: "@Url.Action("DeleteEmail","Home")",
                data: { id: id },
                success: function (data)
                {
                    if (data.Success)
                    {
                        var row = btn.parentNode.parentNode;
                        row.parentNode.removeChild(row);
                    }
                    else
                    {
                        alert(data.Message);
                    }
                },
                error: function (data)
                {
                    alert(data.Message);
                },
                datatype: 'json'
            });
        }
    </script>
}